#!/usr/bin/env python3
##
## PERSONAL PROJECT, 2020
## Fractal Tree
#!

import turtle

def tree(len, mem, angle, t):
    if len > mem/10:
        t.forward(len)
        t.right(angle)
        tree(len - 10, mem, angle, t)
        t.left(angle * 2)
        tree(len - 10, mem, angle, t)
        t.right(angle)
        t.backward(len)

def function(len, angle):
    t = turtle.Turtle()
    screen = turtle.Screen()
    screen.setup(len * 10, len * 6)
    t.speed(1000000)
    t.left(90)
    t.up()
    t.backward(len * 3)
    t.down()
    tree(len, len, angle, t)
    screen.exitonclick()

def val_input():
    len = input("What size for the fractal tree ? ")
    angle = input("What angle for the fractal tree ? ")
    try :
        int(len)
        int(angle)
    except ValueError :
        print ("Wrong size input")
        exit(84)
    len = int(len)
    angle = int(angle)
    function(len, angle)

val_input()