#!/usr/bin/env python3
##
## PERSONAL PROJECT, 2020
## Fractal Tree
#!

import turtle

def tree(len, mem, t):
    if len > mem/10:
        t.forward(len)
        t.right(25)
        tree(len - 10, mem, t)
        t.left(50)
        tree(len - 10, mem, t)
        t.right(25)
        t.backward(len)

def function():
    len = 100
    t = turtle.Turtle()
    screen = turtle.Screen()
    t.speed(1000000)
    t.left(90)
    t.up()
    t.backward(300)
    t.down()
    tree(len, len, t)
    screen.exitonclick()

function()