#!/usr/bin/env python3
##
## PERSONAL PROJECT, 2020
## Fractal Tree
#!

import turtle

def tree(len, t):
    if len > 2:
        t.forward(len)
        t.right(25)
        tree(len / 2, t)
        t.left(50)
        tree(len / 2, t)
        t.right(25)
        t.backward(len)

def function():
   t = turtle.Turtle()
   data = turtle.Screen()
   t.left(90)
   t.up()
   t.backward(100)
   t.down()
   tree(100, t)
   data.exitonclick()

function()